main/main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tera', include('ra.urls', namespace = 'ra')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/ra/urls.py
from django.urls import path
from . import views

app_name = 'ra'
urlpatterns = [
	
			path('', views.TeraIndexView.as_view(), name="index_view"),
			path('/login', views.TeraLoginUser.as_view(), name='tera_login_view'),
			path('/dashboard',views.TeraDashboardView.as_view(), name="tera_dashboard_view"),
			path('/accountsettings', views.TeraAccountSettingsView, name='tera_account_settings'),
			path('/search',views.TeraSearchResultsView.as_view(), name="search_result_view"),
			path('/admin', views.adminIndexView.as_view(), name="admin_index_view"),
			path('/admin/charts', views.adminChartView.as_view(), name="admin_chart_view"),
			path('/admin/table', views.adminTableView.as_view(), name="admin_table_view"),
			path('/practice', views.practice.as_view(), name="practice"),
			path('/practice2/search?=<sinput>&site=<site>&type=<type>', views.practice2.as_view(), name="practice2"),
			path('/practice3', views.practice3.as_view(), name="practice34"),
			
			]	

main/ra/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.models import AbstractUser



class Department (models.Model):
	abbv = models.CharField(max_length=50, null = False, blank= False, default='')
	name = models.CharField(max_length=200, null = False, blank= False)
	class Meta:
		db_table = "Department"

class User (AbstractUser):

	department= models.ForeignKey(Department, null = False, blank = False, on_delete = models.CASCADE)

	REQUIRED_FIELDS = ['first_name', 'last_name','department','password']
	class Meta:
		db_table = "User"


class Admin (models.Model):
	user = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE)
	department_id= models.ForeignKey(Department, null = False, blank = False, on_delete = models.CASCADE)
	class Meta:
		db_table = "Admin"



class User_bookmark (models.Model):
	websiteTitle = models.CharField(max_length = 1000, null = False)
	itemType = models.CharField(max_length = 50,null=False)
	url = models.CharField(max_length = 2000,null=False)
	title = models.CharField(max_length = 1000,null=False)
	subtitle = models.CharField(max_length = 1000,null=True)
	author =  models.CharField(max_length = 1000,blank= True)
	description =  models.CharField(max_length = 1000,blank= True)
	journalItBelongs = models.CharField(max_length = 1000,blank= True)
	volume = models.IntegerField(blank= True)
	numOfCitation = models.CharField(max_length = 1000,blank= True)
	numOfDownload = models.CharField(max_length = 1000,blank= True)
	numOfPages = models.CharField(max_length = 1000,blank= True)
	edition =models.CharField(max_length = 20,blank= True)
	publisher = models.CharField(max_length = 1000, blank= True)
	publicationYear = models.CharField(max_length= 20,blank= True)
	dateAccessed = models.DateTimeField(default = datetime.now())
	dateAdded = models.DateTimeField(default=datetime.now() )
	DOI = models.CharField(max_length = 200,blank= True)
	ISSN = models.CharField(max_length = 100,blank= True)
	isRemoved = models.IntegerField(default = 0)
	user = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE)
	isFavorite = models.BooleanField(default=False)
	date_removed = models.DateTimeField(blank = True, null = True)

	class Meta:
		db_table = "User_bookmark"

class Dissertation(models.Model):
	title = models.CharField(max_length=1000)
	abstract = models.CharField(max_length=2000)

	class Meta:
		db_table = "Dissertation"

class Dissertation_authors(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=30)
	dissertation = models.ForeignKey(Dissertation, null = False, blank = False, on_delete = models.CASCADE)

	class Meta:
		db_table = "Dissertation_authors"


class User_file(models.Model):
	user = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE)
	file = models.FileField(upload_to ='media', null = False)
	class Meta:
		db_table = "User_files"


class Group(models.Model):
	name = models.CharField(max_length=50) #add not null and not blank here
	description = models.CharField(max_length=200)
	owner = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE)
	date_created = models.DateTimeField(default=datetime.now())
	class Meta:
		db_table = "Group"

class Group_member(models.Model):
	group = models.ForeignKey(Group, null = False, blank = False, on_delete = models.CASCADE)
	user = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE)
	class Meta:
		db_table = "Group_member"

class Group_bookmark(models.Model):
	group =models.ForeignKey(Group, null = False, blank = False, on_delete = models.CASCADE)
	bookmark = models.ForeignKey(User_bookmark, null = False, blank = False, on_delete = models.CASCADE)
	added_by = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE)
	date_added = models.DateTimeField(default=datetime.now())
	is_removed = models.IntegerField(default=0)
	date_removed = models.DateTimeField(blank=True,null = True)

	class Meta:
		db_table = "Group_bookmark"


class Folder(models.Model):
	name = models.CharField(max_length=25, unique=True)
	user = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE, default=None)
	date_created = models.DateTimeField(default=datetime.now())

	class Meta:
		db_table = "Folder"	

class Bookmark_folder (models.Model):
	user = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE)
	folder = models.ForeignKey(Folder, null = False, blank = False, on_delete = models.CASCADE)
	bookmark = models.ForeignKey(User_bookmark, null = False, blank = False, on_delete = models.CASCADE)
	date_added = models.DateTimeField(default=datetime.now())
	is_removed = models.IntegerField(default=0)
	date_removed = models.DateTimeField(blank=True,null = True)

	class Meta:
		db_table = "Bookmark_folder"	


	


	



class Site (models.Model):
	name = models.CharField(max_length= 100)
	url= models.CharField(max_length= 300)
	added_by = models.ForeignKey(Admin, null = False, blank = False, on_delete = models.DO_NOTHING)
	date_added = models.DateTimeField(default=datetime.now())

	class Meta:
		db_table = "Site"	


class User_access (models.Model):
	user = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE)
	department = models.ForeignKey(Department, null = False, blank = False, on_delete = models.CASCADE)
	site = models.ForeignKey(Site, null = False, blank = False, on_delete = models.CASCADE)
	date_of_access = models.DateTimeField(default=datetime.now())

	class Meta:
		db_table = "User_access"	


class Headers (models.Model):
	text = models.CharField(max_length = 5000)

	class Meta:
		db_table = "Headers"


class Practice (models.Model):
	text =  models.CharField(max_length = 5)
	time = models.DateTimeField(default=datetime.now())


	class Meta:
		db_table = "Practice"



class Proxies (models.Model):
	proxy = models.CharField(max_length = 100)
	isUsed = models.BooleanField(default = False)

	class Meta:
		db_table = "Proxies"

main/ra/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User


		#fields = '__all__'

class CreateFolderForm(forms.ModelForm):
	class Meta:
		model = Folder
		fields = ('name',)

class LoginUser(UserCreationForm):
	class Meta:
		model = User
		fields = [ 'username', 'password' ]



		

main/ra/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import HttpResponse
from .forms import CreateFolderForm
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from bs4 import BeautifulSoup
from .links import *
import requests
from fake_useragent import FakeUserAgent
import ast
import json
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from django.http import JsonResponse
from django.db import connection
import MySQLdb as mdb
from datetime import datetime
from django.core import serializers
from django.db.models import Q

class adminIndexView(View):
	def get(self, request):
		print('olok')
		
		return render(request,'adminIndex.html')
class practice2(View):
	def get(self, request, sinput, site,type):
		print('olok')
		
		return HttpResponse(sinput +" "+site+" "+type)


		

class practice3(View):
	
	def get(self, request):
		return HttpResponse(self.a)
	def post(self, request):
		if request.method == 'POST' and request.is_ajax():
			print('practice 3 post')

			
			return HttpResponse(request.GET.get('search'))
		
		
		


class practice(View):
	
	def get(self, request):
		# Department.objects.create(name='College of Computer Studies', abbv='CCS')
		# User.objects.create(username='mondejar', password =make_password('12345'), department=Department.objects.get(abbv='CCS'))
		# User.objects.create(username='mondejar2', password = make_password('mondejar.12345'), department_id=2)
		

		# cursor = connection.cursor()   
		#datetime.now().month = #get month of current time
		# cursor.execute("SELECT b.isRemoved, COUNT(b.user_id) FROM auth_user u, bookmarks b WHERE u.id=b.user_id AND b.dateAdded LIKE '2021-11%' GROUP BY isRemoved") #| get rows of for a specific date|
		# cursor.execute("SELECT user_id, COUNT(user_id) AS `value_occurrence` FROM Bookmarks GROUP BY user_id ORDER BY `value_occurrence` DESC LIMIT 1") # |get the most frequent user ID (top1 ky limit 1 man)|
		# cursor.execute("Select b.* from Bookmarks b, bookmark_folders bf Where bf.user_id = "+str(request.user.id)+" AND bf.folder_id = "+ str(1)+" AND bf.bookmark_id = b.id"  ) #|for retrievving bookmarks inside a folder|
		# row = cursor.fetchall()
		
		# queryset = User.objects.filter(id = Bookmarks.objects.filter(dateAdded__contains='2021-11-17').values('user_id'))   #| get rows of for a specific date|
		# row = cursor.fetchall()
		# print()

		# cursor.execute("SELECT id, COUNT(id) FROM Bookmarks GROUP BY dateAdded LIKE '2021-11%'") # |get the most frequent user ID (top1 ky limit 1 man)|
		# row = cursor.fetchall()
		# print(row)
		# queryset = User_bookmark.objects.all()
		# a = list(queryset)
		# context = {
		#     "bookmark_set": queryset,
		#     # "bookmark_list" : a 
		# }
		# return HttpResponse()
		
		return render(request,'practice.html')#,context)

	def post(self, request):
		
		if request.method == 'POST':
			

			return HttpResponse('practice post')
			
		
		


class TeraLoginUser(View): 

	def get(self,request):
		# proxies = proxy_generator2() #/ generating free proxies /
		# for proxy in proxies:  #/ saving proxies to db /
			
		# 	proxy = Proxies(proxy = proxy)
		# 	proxy.save()
		
		if( request.user.id != None):
			try:
				return redirect("ra:" + request.session.get('previousPage'))
			except:
				request.session['previousPage'] = 'index_view'
				return redirect("ra:index_view")
		else:
			
			return render(request,'login.html')	
		
		

	def post(self, request):
		
	
		
		if 'buttonlogin' in request.POST:
			print('Login Button CLiked!')
			username = request.POST.get('username')
			password = request.POST.get('password')

			user = authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				
				if request.session.get('proxy') == None:
					proxies = Proxies.objects.filter(isUsed = 0) # get all proxy from db
					request.session['proxy'] = testProxy(proxies,1)
					
				return redirect('ra:'+ request.session.get('previousPage'))
			else:
				return render(request,'loginInvalid.html')
		
		
					
		
		 
			
class TeraIndexView(View):
	def get(self, request):
		

		#proxies = proxy_generator2() #/ generating free proxies /
		#for proxy in proxies:  #/ saving proxies to db /
			
		#	proxy =Proxies(proxy = proxy)
		#	proxy.save()
		
		if request.session.get('proxy') == None:
			proxies = Proxies.objects.filter(isUsed = 0) # get all proxy from db
			request.session['proxy'] = testProxy(proxies,1)
		else:
			result = testProxy(request.session.get('proxy'),2) # test a single proxy

			if result == False:
				proxies = Proxies.objects.filter(isUsed = 0) # get all proxy from db
				request.session['proxy'] = testProxy(proxies,1) # test a random proxy from db
			else:
				request.session['proxy'] = result

		request.session['previousPage'] = 'index_view'
		
		context ={
			"user_id": request.user.id
		}
		
	
		
		#x = Proxies.objects.filter(id = proxyID.id).update(isUsed = 1)
		return render(request,'landingpage.html',context)

	def post(self, request):

		if 'buttonLogin' in request.POST:
			request.session['previousPage'] = request.POST['previousPage']
			print(request.session.get('previousPage'))
			return redirect('ra:tera_login_view')

		elif 'btnLogout' in request.POST:
			proxy = request.session.get('proxy')

			logout(request)

			request.session['proxy'] = proxy
			return redirect("ra:index_view")

		elif 'btnSearch' in request.POST:
			request.session['word'] = request.POST.get("keyword")
			
			return redirect('ra:search_result_view')
		


class TeraSearchResultsView(View):
	

	def get(self,request):
		request.session['previousPage'] ='search_result_view'
		# header = ast.literal_eval(Headers.objects.get(id=2).text)	# converting b from string to dictionary
		# header = request.session.get('header')
		word = request.session.get('word')

		proxy = request.session.get('proxy')

		if request.session.get('website') != None:
			website = request.session.get('website')
		else:
			website = "Springeropen.com"

		if request.session.get('itemType') != None:
			itemType = request.session.get('itemType')
		else:
			itemType = "article"
						
		context = {
							'keyword': word,
							'proxy': proxy,
							'website': website,
							'itemType': itemType,
							'is_authenticated': str(request.user.is_authenticated)
		}
		
		return render(request,'searchresults.html', context)

	def post(self, request):
		
		if request.method == 'POST' and request.is_ajax():
			
			
			
			action = request.POST['action']

			if action == "search":


				if request.POST['proxy'] == None:
					proxies = Proxies.objects.filter(isUsed = 0) # get all proxy from db
					proxy = testProxy(proxies,1)


					word = request.POST['word']
					website = request.POST['site']
					itemType = request.POST['itemType']
					request.session['website'] =website
					request.session['itemType'] = itemType
					request.session['word'] = word

					a = scrape(word,proxy,itemType , website,' ', request.POST['pageNumber'])
					
					while (a == False):
						proxies = Proxies.objects.filter(isUsed = 0) # get all proxy from db
						proxy = testProxy(proxies,1)
						request.session['proxy'] = proxy
						a = scrape(request.POST['word'],proxy, itemType,website ,' ', request.POST['pageNumber'])
				


					results = a[0]	
					links = a[1]
					# print(results)
					context = {
						'results': results,
						'links': links,
						'proxy': proxy,
						'is_authenticated': request.user.is_authenticated
					}
					return JsonResponse(context)





				else:
					print("search")
					word = request.POST['word']
					request.session['word'] = word
					proxy = request.POST['proxy']
					
					website = request.POST['site']
					itemType = request.POST['itemType']
					request.session['website'] =website
					request.session['itemType'] = itemType


					a = scrape(word,proxy,itemType , website,' ', request.POST['pageNumber'])
					
					while (a == False):
						proxies = Proxies.objects.filter(isUsed = 0) # get all proxy from db
						proxy = testProxy(proxies,1)
						request.session['proxy'] = proxy
						a = scrape(request.POST['word'],proxy, itemType,website ,' ', request.POST['pageNumber'])
				


					results = a[0]	
					links = a[1]
					# print(results)
					context = {
						'results': results,
						'links': links,
						'proxy': proxy,
						'is_authenticated': request.user.is_authenticated
					}
					return JsonResponse(context)
					
			elif action == "add":
				print('bookmark button clicked')
				bookmark = request.POST['bookmark']
				siteRef = request.POST['website'] +" " +request.POST['reftype']
				string = bookmark.split('||')
				title = string[0].replace('\n','').replace('  ','')
				url = string[1]
				# print(title, url, siteRef)
				detail = details(url, request.session.get('proxy'),siteRef)

				websiteTitle = detail['websiteTitle']
				itemType = detail['itemType']
				author = detail['author']
				description = detail['description']
				journalItBelongs = detail['journalItBelongs']
				volume = detail['volume']
				doi = detail['doi']
				publicationYear = detail['publishYear']
				subtitle = detail['subtitle']
				citation = detail['citation']
				downloads = detail['downloads']
				publisher = detail['publisher']
				edition = detail['edition']
				pages = detail['pages']
				# author description publication volume doi
				
				
				# print(websiteTitle + '\n'+itemType + '\n'+title + '\n' +link + '\n' +author+ '\n' +description+ '\n' +publication+ '\n' +volume+ '\n' +doi)
				if request.POST['reftype'] == "article":

main/ra/templates/1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	
	<title>Landing Page</title>

	<link rel="stylesheet" type="text/css" href="{% static 'css/1.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/1.css' %}">
</head>

<body >
<div style="height: 80px; background-color: #eee7e7">
	<div> 

		<div style="font-size: 35px; color: #7e320d; padding-top: 15px; padding-left: 65%; font-family: Calibri 		light; font-weight: bold;">
					About us
		</div>
		
		<div style="margin-top: -45px; margin-left: 80%"> <button style="border-radius: 50px; height: 50px; width: 100px; outline: none; color: 7e320d; font-size: 20px; border-color: yellow"> Login </button> 


		</div> 
			
	</div>
	<div style=" background-image: url({% static 'images/bg.png' %}); margin-top: 19px;width: 100%; height: 700%; "> 
		

		<div style="color: white; font-size: 50px; font-family: Calibri light; font-weight: bold; "> 
				<center style="padding-top: 10%" >Exclusive Research Assistant </center>
				<center> for Teknoys</center>
		</div>

		<center >
			<div class="search" >
				<input type="text" name="" style="background-color: #efefef; width: 85%; height: 32px; margin-top: 4px;  float: left; margin-left: 10px; border-color: white; outline: none; border-top-left-radius: 20px 20px; border-bottom-left-radius: 20px 20px" placeholder="Search..."> 
				
				
			</div>
		</center>

	</div>

	



</div>
</body>
</html>

main/ra/templates/adminCharts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>TERA</title>
        <link href="{% static 'css/adminStyles.css' %}" rel="stylesheet" /> 
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">TERA</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="index.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Layouts
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Pages
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="login.html">Login</a>
                                            <a class="nav-link" href="register.html">Register</a>
                                            <a class="nav-link" href="password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>
                            <div class="sb-sidenav-menu-heading">Addons</div>
                            <a class="nav-link" href="{% url 'ra:admin_chart_view' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Charts
                            </a>
                            <a class="nav-link" href="{% url 'ra:admin_table_view' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Tables
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">Charts</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="{% url 'ra:admin_index_view' %}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Charts</li>
                        </ol>
                        <div class="card mb-4">
                            <div class="card-body">
                                Chart.js is a third party plugin that is used to generate the charts in this template. The charts below have been customized - for further customization options, please visit the official
                                <a target="_blank" href="https://www.chartjs.org/docs/latest/">Chart.js documentation</a>
                                .
                            </div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-chart-area me-1"></i>
                                Active Users
                            </div>
                            <div class="card-body"><canvas id="myAreaChart" width="100%" height="30"></canvas></div>
                            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-bar me-1"></i>
                                        Search Results
                                    </div>
                                    <div class="card-body"><canvas id="myBarChart" width="100%" height="50"></canvas></div>
                                    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-pie me-1"></i>
                                        Pie Chart Example
                                    </div>
                                    <div class="card-body"><canvas id="myPieChart" width="100%" height="50"></canvas></div>
                                    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; TERA 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/adminScripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'adminAssets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'adminAssets/demo/chart-bar-demo.js' %}"></script>
        <script src="{% static 'adminAssets/demo/chart-pie-demo.js' %}"></script>
    </body>
</html>